"""add name to user model

Revision ID: 2875b95cb02
Revises: 2260b085d6a
Create Date: 2015-11-03 17:45:09.596179

"""

# revision identifiers, used by Alembic.
revision = '2875b95cb02'
down_revision = '2260b085d6a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():

    # add the new column, the server_default parameter
    op.add_column('user', sa.Column('name', sa.String(length=50), server_default='', nullable=False))



def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'name')
    ### end Alembic commands ###
